services:
  frontend:
    image: events-app-frontend:latest
    build: .
    ports:
      - "5573:80"
    deploy:
      restart_policy:
        condition: on-failure
    volumes: # mount config
      - '${PWD}/public/config.js:/usr/share/nginx/html/config.js'

