import ArrowDown from "./svg/ArrowDown.svg?react";
import ArrowLeft from "./svg/ArrowLeft.svg?react";
import ArrowRight from "./svg/ArrowRight.svg?react";
import Home from './svg/Home.svg?react';
import ITMOLogo from "./svg/ITMOLogo.svg?react";
import Menu from './svg/Menu.svg?react';
import Noted from './svg/Noted.svg?react';
import ReactLogo from "./svg/ReactLogo.svg?react";
import Users from './svg/Users.svg?react';
import ViteLogo from "./svg/ViteLogo.svg?react";
import Search from "./svg/Search.svg?react";
import MenuVertical from "./svg/MenuVertical.svg?react";
import Personal from "./svg/Personal.svg?react";
import UserCard from "./svg/UserCard.svg?react";
import DocumentCheck from "./svg/DocumentCheck.svg?react";
import UserRead from "./svg/UserRead.svg?react";
import Notebook from "./svg/Notebook.svg?react";
import LocationIcon from "./svg/LocationIcon.svg?react";
import CloudUpload from "./svg/CloudUpload.svg?react";

export { ArrowDown, ArrowLeft, ArrowRight, Home, Menu, Noted, ReactLogo, ViteLogo, Users, ITMOLogo, Search, MenuVertical, Personal, UserCard, DocumentCheck, UserRead, Notebook, LocationIcon, CloudUpload};
