name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['21.x']

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build & Push Docker Image
        if: always()
        uses: niqzart/ffs-devops/docker-build@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: event-app-${{ github.event.repository.name }}
          tag: ${{ github.ref_name == 'main' && 'latest' || needs.namer.outputs.tag }}
          base-tag: latest
          dockerfile: "./dockerfile-runner"
